---CASE 1- CUSTOMER DATABASE




-- Q1. Customers tablosunda adý "A" harfi ile baþlayan  10 kiþiyi  çekiniz.
SELECT TOP 10 * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'A%'

-- Q2. Customers tablosunda adý "N" harfi ile biten ve cinsiyeti erkek olan 10 kiþiyi sýralayýnýz.
SELECT TOP 10 * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE '%N' AND GENDER = 'E'

--Q3. 1990 ile 1995 yýllarý arasýnda doðan müþterileri çekiniz. 90ve95 de dahildir.
SELECT TOP 10 * FROM CUSTOMERS
WHERE BIRTHDATE BETWEEN '1990-01-01' AND '1995-12-31'
--OR
SELECT TOP 10 * FROM CUSTOMERS
WHERE YEAR(BIRTHDATE) BETWEEN 1990 AND 1995

--Q4. Istanbul'da yaþayan kiþileri Join kullanarak getiren sorguyu yazýnýz.

SELECT TOP 10 C.*,CT.CITIES FROM CUSTOMERS C
INNER JOIN CITIES CT ON C.CITYID = CT.ID
WHERE CT.CITIES ='ÝSTANBUL'

--Q5. Istanbul'da yaþayan kiþileri subquery kullanarak getiren sorguyu yazýnýz.
SELECT TOP 10 * FROM CUSTOMERS
WHERE CITYID = (SELECT ID FROM CITIES WHERE CITIES ='ÝSTANBUL')

--Q6. Hangi Þehirde Kaç müþterimizin olduðu bilgisini getiren sorguyu yazýnýz.
SELECT CT.CITIES,COUNT(C.ID) AS CUSTOMERCOUNT FROM CUSTOMERS C
INNER JOIN CITIES CT ON C.CITYID=CT.ID
GROUP BY CT.CITIES
--SOLUTION2.

SELECT *,
(SELECT COUNT(*) FROM CUSTOMERS C WHERE CITYID=CITIES.ID) AS CUSTOMERCOUNTS 
FROM CITIES

--Q7. 10'dan fazla müþterimiz olan þehirleri müþteri sayýsý ile birlikte müþteri sayýsýna göre fazladan aza doðru sýralý þekilde getiriniz.
SELECT CT.CITIES, COUNT(C.ID) AS COUNTCUSTOMER FROM CUSTOMERS C
INNER JOIN CITIES CT ON C.CITYID=CT.ID
GROUP BY CT.CITIES
HAVING COUNT(C.ID)>10 
ORDER BY COUNTCUSTOMER DESC
--OR
SELECT CITIES, 
(SELECT COUNT(CITYID)FROM CUSTOMERS C WHERE C.CITYID =CITIES.ID ) AS CUSTOMERCOUNT
FROM CITIES
WHERE (SELECT COUNT(CITYID)FROM CUSTOMERS C WHERE C.CITYID =CITIES.ID )>10
ORDER BY CUSTOMERCOUNT DESC

--Q9. Hangi þehirde kaç erkek, kaç kadýn müþterimiz olduðu bilgisini getiren sorguyu yazýnýz.

SELECT CT.CITIES,C.GENDER,COUNT(C.ID) AS CUSTOMERCOUNT FROM CUSTOMERS C
INNER JOIN CITIES CT ON C.CITYID=CT.ID
GROUP BY CT.CITIES, C.GENDER
ORDER BY CITIES ASC

--Q10. Hangi þehirde kaç erkek, kaç kadýn müþterimizin olduðu bilgisini erkeksayýsý ve kadýnsayýsý columnlarý yaratarak getiren sorguyu yazýnýz

SELECT CITIES, 
(SELECT COUNT(*)FROM CUSTOMERS  WHERE CITYID=CT.ID AND GENDER ='E') AS ERKEKSAYISI,
(SELECT COUNT(*)FROM CUSTOMERS  WHERE CITYID=CT.ID AND GENDER ='K') AS KADINSAYISI
FROM CITIES CT

--Q11. Customers tablosuna yaþ grubu için yeni bir alan ekleyiniz. Bu iþlemi hem management studio ile hem de sql kodu ile yapýnýz. (Adý AGEGROUP veri tipi VARCHAR(50))

ALTER TABLE CUSTOMERS ADD AGEGROUP VARCHAR(50)

--Q12. Customers tablosuna eklediðiniz AGEGROUP alanýný 20-35 yaþ arasý, 36-45 yaþ arasý, 46-55 yaþ arasý, 55-65 yaþ arasý ve 65 yaþ üstü olarak güncelleyiniz

UPDATE CUSTOMERS 
SET AGEGROUP =
(CASE
WHEN (select YEAR(getdate()) - YEAR(CUSTOMERS.BIRTHDATE)) BETWEEN 20 AND 35 THEN '20-35 YAÞ'
WHEN (select YEAR(getdate()) - YEAR(CUSTOMERS.BIRTHDATE)) BETWEEN 36 AND 45 THEN '36-45 YAÞ'
WHEN (select YEAR(getdate()) - YEAR(CUSTOMERS.BIRTHDATE)) BETWEEN 46 AND 55 THEN '46-55 YAÞ'
WHEN (select YEAR(getdate()) - YEAR(CUSTOMERS.BIRTHDATE)) BETWEEN 55 AND 65 THEN '55-65 YAÞ'
WHEN (select YEAR(getdate()) - YEAR(CUSTOMERS.BIRTHDATE)) > 65 THEN '65 YAÞ ÜSTÜ'
END)

--SELECT TOP 10* FROM  CUSTOMERS
--SELECT DATEDIFF(YEAR,BIRTHDATE,GETDATE()) FROM CUSTOMERS	              

--Q13. Customers tablosunda müþterinin yaþýna göre hesaplanarak, hangi yaþ aralýðýnda kaç kiþi olduðunu getiren sorguyu yazýnýz.
-- OLUÞTURULAN AGE GROUP COLUMNUNU KULLANMADAN YAZ. EÐER ONLA YAZSAYDIK COK BASITTI. ASAGIDAKI.
SELECT COUNT(C.ID),C.AGEGROUP FROM CUSTOMERS C
GROUP BY C.AGEGROUP

-- OLUSTURMADAN YAZILAN YANI DINAMIK OLARAK YAZALIM..
SELECT COUNT(*) AS CUSTOMERCOUNT,
CASE
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAÞ'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 YAÞ'
    WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 YAÞ'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN '56-65 YAÞ'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) >65 THEN  '65 YAÞ ÜSTÜ'
END AGEGROUP2
FROM CUSTOMERS
GROUP BY 
CASE
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAÞ'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 YAÞ'
    WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 YAÞ'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN '56-65 YAÞ'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) >65 THEN  '65 YAÞ ÜSTÜ'
END
ORDER BY AGEGROUP2


-- GROUP BY YAPARKEN TEKRAR CASE YAZDIK BUNUN ONUNE GECMEK ICIN YUKARIDAKI CASE'E BI ISIM VERIP YAZABILIRIZ(Dynamic view). þöyle ki.

SELECT AGEGROUP2,COUNT(TMT.ID) AS CUSTOMERCOUNT FROM 
(SELECT *,
CASE
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAÞ'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 YAÞ'
    WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 YAÞ'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN '56-65 YAÞ'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) >65 THEN  '65 YAÞ ÜSTÜ'
END AGEGROUP2
FROM CUSTOMERS) TMT
GROUP BY AGEGROUP2
ORDER BY AGEGROUP2

 --Q14. Ýstanbul'da yaþayýp ilçesi "Kadýköy" dýþýnda olanlarý listeleyiniz.

 SELECT TOP 10 C.*,CT.CITIES,D.DISTRICT FROM CUSTOMERS C
 INNER JOIN DISTRICTS D ON C.DISTRICTID=D.ID
 INNER JOIN CITIES CT ON C.CITYID=CT.ID
 WHERE CT.CITIES='ÝSTANBUL' AND D.DISTRICT != 'KADIKÖY'


 SELECT * FROM CUSTOMERS
 WHERE CITYID IN(SELECT ID FROM CITIES WHERE CITIES IN ('ÝSTANBUL')) 
 AND
 DISTRICTID NOT IN (SELECT ID FROM DISTRICTS WHERE DISTRICT IN('KADIKÖY'))

 --Q15. Cities tablosundan "Ankara" kaydýný sildiðimizi varsayalým. Bu durumda þehri "Ankara" olan müþterilerin þehir alaný boþ gelecektir. Þehir alaný boþ olan müþterileri listeleyen sorguyu yazýnýz.
 --Önce ankarayý silelim.
 UPDATE CITIES SET CITIES = NULL WHERE ID= 6
 SELECT * FROM CITIES
--Ankarayý tekrar eklemek için
UPDATE CITIES SET CITIES='Ankara' WHERE ID=6
SET IDENTITY_INSERT CITIES ON -- ID deðerimixz identity_insert off modundaydý önce onu açmamýz lazým.
INSERT INTO CITIES(ID,CITIES)
VALUES(6,'ANKARA')
SET IDENTITY_INSERT CITIES OFF -- ID için idendity_insert deðerini kapattýk.
--
 SELECT TOP 10 * FROM CUSTOMERS C
 WHERE C.CITYID  = ( SELECT CT.ID FROM CITIES CT WHERE CT.CITIES IS NULL)

SELECT * FROM CUSTOMERS C
RIGHT JOIN CITIES CT ON C.CITYID=CT.ID
WHERE CT.ID ='6'

 --Q16. Müþterilerimizin telefon numaralarýnýn operatör bilgisini getirmek istiyoruz.(TELN1 ve TELNR2 alanlarýnýn yanýna operatör numarasýný (532)(505) getirmek istiyoruz.) Bu sorgu için gereken SQL sorgusunu yazýnýz.
 SELECT TOP 10 *,
 SUBSTRING(TELNR1,2,3) AS OPERATOR1,
 SUBSTRING(TELNR2,2,3) AS OPERATOR2
 FROM CUSTOMERS

 varchar(5)
 --ADD OPERATOR1 Varchar(5)

 UPDATE CUSTOMERS
 SET OPERATOR1 = ()
 SELECT * FROM CUSTOMERS
 
 --Q17. Müþterilerimizin telefon numaralarýnýn operatör bilgisini getirmek istiyoruz. Örneðin telefon numaralarý "50"ya da "55"ile baþlayan X, "54" ile baþlayan Y, "53" ile baþlayan Z operatörü olsun. Burada hangi operatörden ne kadar müþterimiz olduðunu bilgisini getirecek sorguyu yazýnýz.
 SELECT *,
 CASE
	WHEN CUSTOMERS.TELNR1  LIKE '(50%' OR CUSTOMERS.TELNR1 LIKE '(55%' THEN 1
	ELSE 0
	END AS TELNR1_X,
	CASE
	WHEN CUSTOMERS.TELNR1  LIKE '(54%' THEN 1
	ELSE 0
	END AS TELNR1_Y,
	CASE
	WHEN CUSTOMERS.TELNR1  LIKE '(53%' THEN 1
	ELSE 0
	END AS TELNR1_Z,
	CASE
	WHEN CUSTOMERS.TELNR2  LIKE '(50%' OR CUSTOMERS.TELNR1 LIKE '(55%' THEN 1
	ELSE 0
	END AS TELNR2_X,
	CASE
	WHEN CUSTOMERS.TELNR2   LIKE '(54%' THEN 1
	ELSE 0
	END AS TELNR2_Y,
	CASE
	WHEN CUSTOMERS.TELNR2  LIKE '(53%' THEN 1
	ELSE 0
	END AS TELNR2_Z
	FROM CUSTOMERS

	--BURADA HEPSI ICIN BIR COLUMN OLUSTURDUK SIMDI TOPLAMA ISI VAR.....


	SELECT SUM(TELNR1_X + TELNR2_X) AS OPERATOR_X,
	SUM(TELNR1_Y + TELNR2_Y) AS OPERATOR_Y,
	SUM(TELNR1_Z + TELNR2_Z) AS OPERATOR_Z
	FROM(SELECT *,
 CASE
	WHEN CUSTOMERS.TELNR1  LIKE '(50%' OR CUSTOMERS.TELNR1 LIKE '(55%' THEN 1
	ELSE 0
	END AS TELNR1_X,
	CASE
	WHEN CUSTOMERS.TELNR1  LIKE '(54%' THEN 1
	ELSE 0
	END AS TELNR1_Y,
	CASE
	WHEN CUSTOMERS.TELNR1  LIKE '(53%' THEN 1
	ELSE 0
	END AS TELNR1_Z,
	CASE
	WHEN CUSTOMERS.TELNR2  LIKE '(50%' OR CUSTOMERS.TELNR1 LIKE '(55%' THEN 1
	ELSE 0
	END AS TELNR2_X,
	CASE
	WHEN CUSTOMERS.TELNR2   LIKE '(54%' THEN 1
	ELSE 0
	END AS TELNR2_Y,
	CASE
	WHEN CUSTOMERS.TELNR2  LIKE '(53%' THEN 1
	ELSE 0
	END AS TELNR2_Z
	FROM CUSTOMERS) TMK







 ------



 SELECT *,
 CASE
	WHEN TELNR1 LIKE '(50%' OR TELNR1 LIKE '(55%' THEN 1
	ELSE 0
END AS TELNR1_X,
 CASE
	WHEN TELNR1 LIKE '(54%' THEN 1
	ELSE 0
END AS TELNR1_Y,
 CASE
	WHEN TELNR1 LIKE '(53%' THEN 1
	ELSE 0
END AS TELNR1_Z,
 CASE
	WHEN TELNR2 LIKE '(50%' OR TELNR2 LIKE '(55%' THEN 1
	ELSE 0
END AS TELNR2_X,
 CASE
	WHEN TELNR2 LIKE '(54%' THEN 1
	ELSE 0
END AS TELNR2_Y,
CASE
	WHEN TELNR2 LIKE '(53%' THEN 1
	ELSE 0
END AS TELNR2_Z
FROM CUSTOMERS

--

SELECT SUM(TELNR1_X + TELNR2_X) AS OPERATOR_X,
SUM(TELNR1_Y + TELNR2_Y) AS OPERATOR_Y,
SUM(TELNR1_Z + TELNR2_Z) AS OPERATOR_Z FROM
(SELECT *,
 CASE
	WHEN TELNR1 LIKE '(50%' OR TELNR1 LIKE '(55%' THEN 1
	ELSE 0
END AS TELNR1_X,
 CASE
	WHEN TELNR1 LIKE '(54%' THEN 1
	ELSE 0
END AS TELNR1_Y,
 CASE
	WHEN TELNR1 LIKE '(53%' THEN 1
	ELSE 0
END AS TELNR1_Z,
 CASE
	WHEN TELNR2 LIKE '(50%' OR TELNR2 LIKE '(55%' THEN 1
	ELSE 0
END AS TELNR2_X,
 CASE
	WHEN TELNR2 LIKE '(54%' THEN 1
	ELSE 0
END AS TELNR2_Y,
CASE
	WHEN TELNR2 LIKE '(53%' THEN 1
	ELSE 0
END AS TELNR2_Z
FROM CUSTOMERS) TT


-- Q18.Her ilde en çok müþteriye sahip olduðumuz ilçeleri müþteri sayýsýna göre çoktan aza doðru sýralý þekilde getiren sorguyu yazýnýz.

SELECT TOP 20 CT.CITIES,D.DISTRICT, COUNT(C.ID) AS CUSTOMERCOUNT FROM CUSTOMERS C
INNER JOIN CITIES CT ON  CT.ID = C.CITYID 
INNER JOIN DISTRICTS D ON D.ID = C.DISTRICTID 
GROUP BY CT.CITIES,D.DISTRICT
ORDER BY 1,3 DESC


--Q.19 Müþterilerin doðum günlerini türkçe haftanýn günleri olarak getiren sorguyu yazýnýz.
SET LANGUAGE English
SELECT TOP 10 CUSTOMERNAME,
DATENAME(DW,BIRTHDATE) AS BIRTHDAY
FROM CUSTOMERS


--ben burada bu yýl hangi güne denk geliri denedim. amacým 7ye bolumden kalan sayýya göre gün tayin etmekti. ama artýk yýllar da iþin içine girince kod daha da uzayacagýndan býraktým. yukarýda sadece o yýlýn gününü öðrenmek istiyor.

SELECT TOP 10 *,
	CASE
		WHEN KMKK.KACGUNGECTI%7 = 0 THEN DATENAME(weekday, GETDATE())
		WHEN KMKK.KACGUNGECTI%7 = 1 THEN DATENAME(weekday, DATEADD(day, -6, GETDATE()))
		WHEN KMKK.KACGUNGECTI%7 = 2 THEN DATENAME(weekday, DATEADD(day, -5, GETDATE()))
		WHEN KMKK.KACGUNGECTI%7 = 3 THEN DATENAME(weekday, DATEADD(day, -4, GETDATE()))
		WHEN KMKK.KACGUNGECTI%7 = 4 THEN DATENAME(weekday, DATEADD(day, -3, GETDATE()))
		WHEN KMKK.KACGUNGECTI%7 = 5 THEN DATENAME(weekday, DATEADD(day, -2, GETDATE()))
		WHEN KMKK.KACGUNGECTI%7 = 6 THEN DATENAME(weekday, DATEADD(day, -1, GETDATE()))
	END AS HANGIGUN
FROM
(SELECT KMK.CUSTOMERNAME, DATEDIFF(DAY,KMK.BIRTHDATE,KMK.TODAYSDATE) AS KACGUNGECTI
FROM 
(SELECT *, GETDATE() AS TODAYSDATE FROM CUSTOMERS) KMK)KMKK


-- Q20. Doðum günü bugün olan müþterileri listeleyiniz.

SELECT * FROM CUSTOMERS
WHERE DATEPART(DAY,BIRTHDATE)=DATEPART(DAY,GETDATE()) AND DATEPART(MONTH,BIRTHDATE)=DATEPART(MONTH,GETDATE()) 
 

